<?php

    use Tivet\Banner\TeamSpeak\Factory;

    return [
        'text' => [
            [
                'value'       => lang('banner.welcome') . " " . Factory::client()->getClientNickname(),
                'size'        => 17,
                'font'        => BASE_DIR . '/resources/font/Exo2-Regular.otf',
                'color'       => '#545353',
                'opacity'     => '',
                'align'       => '  ',
                'valign'      => '',
                'width'       => 850,
                'height'      => '',
                'line_height' => '',
                'x'           => 61.8,
                'y'           => 11,
            ],
            [
                'value'       => Factory::server()->getServerOnlineClientCount(true) . "/" . Factory::server()->getServerMaxClientLimit(),
                'size'        => 17,
                'font'        => BASE_DIR . '/resources/font/Exo2-Regular.otf',
                'color'       => '#FFFFFF',
                'opacity'     => '',
                'align'       => '',
                'valign'      => '',
                'width'       => '',
                'height'      => '',
                'line_height' => '',
                'x'           => 211,
                'y'           => 100,
            ],
            [
                'value'       => Factory::server()->getOnlineAdminCount(),
                'size'        => 17,
                'font'        => BASE_DIR . '/resources/font/Exo2-Regular.otf',
                'color'       => '#FFFFFF',
                'opacity'     => '',
                'align'       => '',
                'valign'      => '',
                'width'       => '',
                'height'      => '',
                'line_height' => '',
                'x'           => 211,
                'y'           => 150,
            ],
            [
                'value'       => Factory::server()->getOnlineSupportCount(),
                'size'        => 17,
                'font'        => BASE_DIR . '/resources/font/Exo2-Regular.otf',
                'color'       => '#FFFFFF',
                'opacity'     => '',
                'align'       => '',
                'valign'      => '',
                'width'       => '',
                'height'      => '',
                'line_height' => '',
                'x'           => 211,
                'y'           => 200,
            ],
            [
                'value'       => Factory::server()->getServerTotalPing() . " ms",
                'size'        => 17,
                'font'        => BASE_DIR . '/resources/font/Exo2-Regular.otf',
                'color'       => '#FFFFFF',
                'opacity'     => '',
                'align'       => '',
                'valign'      => '',
                'width'       => '',
                'height'      => '',
                'line_height' => '',
                'x'           => 391,
                'y'           => 125,
            ],
            [
                'value'       => Factory::server()->getServerTotalPacketLoss() . " %",
                'size'        => 17,
                'font'        => BASE_DIR . '/resources/font/Exo2-Regular.otf',
                'color'       => '#FFFFFF',
                'opacity'     => '',
                'align'       => '',
                'valign'      => '',
                'width'       => '',
                'height'      => '',
                'line_height' => '',
                'x'           => 391,
                'y'           => 175,
            ],
            [
                'value'       => Factory::server()->getServerVersion(),
                'size'        => 17,
                'font'        => BASE_DIR . '/resources/font/Exo2-Regular.otf',
                'color'       => '#FFFFFF',
                'opacity'     => '',
                'align'       => '',
                'valign'      => '',
                'width'       => '',
                'height'      => '',
                'line_height' => '',
                'x'           => 572,
                'y'           => 100,
            ],
            [
                'value'       => Factory::server()->getServerPlatform(),
                'size'        => 17,
                'font'        => BASE_DIR . '/resources/font/Exo2-Regular.otf',
                'color'       => '#FFFFFF',
                'opacity'     => '',
                'align'       => '',
                'valign'      => '',
                'width'       => '',
                'height'      => '',
                'line_height' => '',
                'x'           => 572,
                'y'           => 150,
            ],
            [
                'value'       => Factory::client()->getClientVersion(),
                'size'        => 17,
                'font'        => BASE_DIR . '/resources/font/Exo2-Regular.otf',
                'color'       => '#FFFFFF',
                'opacity'     => '',
                'alVign'      => '',
                'valign'      => '',
                'width'       => '',
                'height'      => '',
                'line_height' => '',
                'x'           => 572,
                'y'           => 200,
            ],
        ],
    ];