<?php

    use Tivet\Banner\TeamSpeak\Factory;

    return [
        'text' => [
            [
                'value'   => lang('banner.welcome') . " " . Factory::client()->getClientNickname(),
                'size'    => 17,
                'font'    => BASE_DIR . '/resources/font/Exo2-Regular.otf',
                'color'   => '#545353',
                'opacity' => 1,
                'align'   => 'left',
                'valign'  => 'top',
                'x'       => 61.8,
                'y'       => 14,
            ],
            [
                'value'   => Factory::server()->getServerOnlineClientCount(true) . "/" . Factory::server()->getServerMaxClientLimit(),
                'size'    => 17,
                'font'    => BASE_DIR . '/resources/font/Exo2-Regular.otf',
                'color'   => '#FFFFFF',
                'opacity' => 1,
                'align'   => 'left',
                'valign'  => 'top',
                'x'       => 211,
                'y'       => 102,
            ],
            [
                'value'   => Factory::server()->getOnlineAdminCount(),
                'size'    => 17,
                'font'    => BASE_DIR . '/resources/font/Exo2-Regular.otf',
                'color'   => '#FFFFFF',
                'opacity' => 1,
                'align'   => 'left',
                'valign'  => 'top',
                'x'       => 211,
                'y'       => 152,
            ],
            [
                'value'   => Factory::server()->getOnlineSupportCount(),
                'size'    => 17,
                'font'    => BASE_DIR . '/resources/font/Exo2-Regular.otf',
                'color'   => '#FFFFFF',
                'opacity' => 1,
                'align'   => 'left',
                'valign'  => 'top',
                'x'       => 211,
                'y'       => 202,
            ],
            [
                'value'   => Factory::server()->getServerTotalPing() . " ms",
                'size'    => 17,
                'font'    => BASE_DIR . '/resources/font/Exo2-Regular.otf',
                'color'   => '#FFFFFF',
                'opacity' => 1,
                'align'   => 'left',
                'valign'  => 'top',
                'x'       => 391,
                'y'       => 127,
            ],
            [
                'value'   => Factory::server()->getServerTotalPacketLoss() . " %",
                'size'    => 17,
                'font'    => BASE_DIR . '/resources/font/Exo2-Regular.otf',
                'color'   => '#FFFFFF',
                'opacity' => 1,
                'align'   => 'left',
                'valign'  => 'top',
                'x'       => 391,
                'y'       => 177,
            ],
            [
                'value'   => Factory::server()->getServerVersion(),
                'size'    => 17,
                'font'    => BASE_DIR . '/resources/font/Exo2-Regular.otf',
                'color'   => '#FFFFFF',
                'opacity' => 1,
                'align'   => 'left',
                'valign'  => 'top',
                'x'       => 572,
                'y'       => 102,
            ],
            [
                'value'   => Factory::server()->getServerPlatform(),
                'size'    => 17,
                'font'    => BASE_DIR . '/resources/font/Exo2-Regular.otf',
                'color'   => '#FFFFFF',
                'opacity' => 1,
                'align'   => 'left',
                'valign'  => 'top',
                'x'       => 572,
                'y'       => 152,
            ],
            [
                'value'   => Factory::client()->getClientVersion(),
                'size'    => 17,
                'font'    => BASE_DIR . '/resources/font/Exo2-Regular.otf',
                'color'   => '#FFFFFF',
                'opacity' => 1,
                'align'   => 'left',
                'valign'  => 'top',
                'x'       => 572,
                'y'       => 202,
            ],
        ],
    ];